void exercicio1(int x, int y);
void exercicio2(int x, int y);
void exercicio4(float salario);
void exercicio3();
void exercicio5();
void exercicio6();
int exercicio7(int base, int expoente);
void exercicio8();
int exercicio9(int n);
void exercicio10();
void exercicio11();
void exercicio12();
